# Generated by Django 4.1.7 on 2023-03-16 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_alter_blogpostmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpostmodel',
            name='description',
            field=froala_editor.fields.FroalaField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='blogpostmodel',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
